// countries.js
export const countries = [
  { name: "Afghanistan", code: "AF", phone: "+93" },
  { name: "Albania", code: "AL", phone: "+355" },
  { name: "Algeria", code: "DZ", phone: "+213" },
  { name: "Andorra", code: "AD", phone: "+376" },
  { name: "Angola", code: "AO", phone: "+244" },
  { name: "Argentina", code: "AR", phone: "+54" },
  { name: "Armenia", code: "AM", phone: "+374" },
  { name: "Australia", code: "AU", phone: "+61" },
  { name: "Austria", code: "AT", phone: "+43" },
  { name: "Azerbaijan", code: "AZ", phone: "+994" },
  { name: "Bahamas", code: "BS", phone: "+1-242" },
  { name: "Bahrain", code: "BH", phone: "+973" },
  { name: "Bangladesh", code: "BD", phone: "+880" },
  { name: "Belgium", code: "BE", phone: "+32" },
  { name: "Benin", code: "BJ", phone: "+229" },
  { name: "Botswana", code: "BW", phone: "+267" },
  { name: "Brazil", code: "BR", phone: "+55" },
  { name: "Bulgaria", code: "BG", phone: "+359" },
  { name: "Burkina Faso", code: "BF", phone: "+226" },
  { name: "Canada", code: "CA", phone: "+1" },
  { name: "China", code: "CN", phone: "+86" },
  { name: "Côte d'Ivoire", code: "CI", phone: "+225" },
  { name: "Denmark", code: "DK", phone: "+45" },
  { name: "Egypt", code: "EG", phone: "+20" },
  { name: "Ethiopia", code: "ET", phone: "+251" },
  { name: "Finland", code: "FI", phone: "+358" },
  { name: "France", code: "FR", phone: "+33" },
  { name: "Germany", code: "DE", phone: "+49" },
  { name: "Ghana", code: "GH", phone: "+233" },
  { name: "Greece", code: "GR", phone: "+30" },
  { name: "India", code: "IN", phone: "+91" },
  { name: "Ireland", code: "IE", phone: "+353" },
  { name: "Italy", code: "IT", phone: "+39" },
  { name: "Japan", code: "JP", phone: "+81" },
  { name: "Kenya", code: "KE", phone: "+254" },
  { name: "Mexico", code: "MX", phone: "+52" },
  { name: "Netherlands", code: "NL", phone: "+31" },
  { name: "Nigeria", code: "NG", phone: "+234" },
  { name: "Norway", code: "NO", phone: "+47" },
  { name: "South Africa", code: "ZA", phone: "+27" },
  { name: "Spain", code: "ES", phone: "+34" },
  { name: "Sweden", code: "SE", phone: "+46" },
  { name: "Switzerland", code: "CH", phone: "+41" },
  { name: "United Arab Emirates", code: "AE", phone: "+971" },
  { name: "United Kingdom", code: "GB", phone: "+44" },
  { name: "United States", code: "US", phone: "+1" },
  { name: "Zimbabwe", code: "ZW", phone: "+263" },
];
